name: ServiceNow CITZ CI Pipeline

on: 
  pull_request:
    branches:
      - main
     
jobs:
  build:
  # Purpose of this job is to execute ATF on current branch
    name: Run ATF on dev instance
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowUsername: ${{ secrets.NOW_INSTANCE_USERNAME }}
          snowPassword: ${{ secrets.NOW_INSTANCE_PASSWORD }}
          snowSourceInstance: ${{ secrets.NOW_INSTANCE }}
          appSysID: ${{ secrets.NOW_APP_SYS_ID }}

      - name: Run Tests 
        id: atf_test_dev
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName:
          browserVersion:
          osName:
          osVersion:
          testSuiteSysId: ${{ secrets.CITZ_TEST_SUITE_ID }}
          testSuiteName:
        env:
          snowUsername: ${{ secrets.NOW_INSTANCE_USERNAME }}
          snowPassword: ${{ secrets.NOW_INSTANCE_PASSWORD }}
          snowInstallInstance: ${{ secrets.NOW_INSTANCE }}
  ServiceNowDevOpsChange:
    # jobs that must complete successfully before this job will run
    needs: build
    # type of machine to run the job on
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
    - name: ServiceNow Change
      uses: ServiceNow/servicenow-devops-change@v3.1.0
      id: create
      with:
        # Devops Integration Token
        devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
        # ServiceNow Instance URL
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        # Orchestration Tool Id
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        # GitHub Context
        context-github: ${{ toJSON(github) }}
        # Display Name of the Job
        job-name: 'ServiceNow DevOps Change'
        change-request: '{"attributes":{"requested_by":{"name": "System Administrator"},"assignment_group":{"name": "DevOps Change Config Admins"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2023-09-07 11:59:59","end_date": "2023-09-09 11:59:59"}}'
        interval: '10'
        timeout: '30'
        changeCreationTimeOut: '30'
        abortOnChangeCreationFailure: true
        abortOnChangeStepTimeout: true
        # You can specify the requested_by attribute either with name or sys_id. Example: "requested_by":{"name": "Test User"} or "requested_by": "62826bf03710200044e0bfc8bcbe5df1"
        # You can specify the assignment_group attribute either with name or sys_id. Example: "assignment_group":{"name": "Change Approval Team"} or "assignment_group": "5f721d93c0a8010e015533746de18bf9"
        # start_date: This is the planned start date
        # end_date: This is the planned end date
